<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
    <RecoveredSourceLibraryMode>Binary</RecoveredSourceLibraryMode>
    <RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SourceLibraries\Whetstone.ChatGPT\Whetstone.ChatGPT.csproj" />
    <Reference Include="Microsoft.Extensions.Options">
      <HintPath>..\..\lib\Microsoft.Extensions.Options.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
