<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>WpfRangeControls</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWPF>True</UseWPF>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableDefaultPageItems>False</EnableDefaultPageItems>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <Page Include="themes\generic.xaml" />
  </ItemGroup>
  <ItemGroup />
</Project>
