<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Utools</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(RecoveredBinaryDirectory)\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.0" />
    <Reference Include="System.Management" />
    <Reference Include="Collections.Pooled">
      <HintPath>$(RecoveredBinaryDirectory)\Collections.Pooled.dll</HintPath>
    </Reference>
    <Reference Include="F23.StringSimilarity">
      <HintPath>$(RecoveredBinaryDirectory)\F23.StringSimilarity.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
